/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifySignupRouteImport } from './routes/verify-signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndicesRouteImport } from './routes/indices'
import { Route as HeatmapRouteImport } from './routes/heatmap'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as StockSymbolRouteImport } from './routes/stock.$symbol'
import { Route as DashboardWatchlistRouteImport } from './routes/dashboard.watchlist'
import { Route as DashboardSentimentRouteImport } from './routes/dashboard.sentiment'
import { Route as DashboardSearchRouteImport } from './routes/dashboard.search'
import { Route as DashboardRecommendationsRouteImport } from './routes/dashboard.recommendations'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardPaperTradingRouteImport } from './routes/dashboard.paper-trading'
import { Route as DashboardHeatmapRouteImport } from './routes/dashboard.heatmap'
import { Route as DashboardAiRouteImport } from './routes/dashboard.ai'
import { Route as DashboardStockSymbolRouteImport } from './routes/dashboard.stock.$symbol'
import { Route as DashboardAiSessionIdRouteImport } from './routes/dashboard.ai.$sessionId'

const VerifySignupRoute = VerifySignupRouteImport.update({
  id: '/verify-signup',
  path: '/verify-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicesRoute = IndicesRouteImport.update({
  id: '/indices',
  path: '/indices',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapRoute = HeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const StockSymbolRoute = StockSymbolRouteImport.update({
  id: '/stock/$symbol',
  path: '/stock/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWatchlistRoute = DashboardWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSentimentRoute = DashboardSentimentRouteImport.update({
  id: '/sentiment',
  path: '/sentiment',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSearchRoute = DashboardSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRecommendationsRoute =
  DashboardRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaperTradingRoute = DashboardPaperTradingRouteImport.update({
  id: '/paper-trading',
  path: '/paper-trading',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHeatmapRoute = DashboardHeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiRoute = DashboardAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStockSymbolRoute = DashboardStockSymbolRouteImport.update({
  id: '/stock/$symbol',
  path: '/stock/$symbol',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiSessionIdRoute = DashboardAiSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => DashboardAiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/disclaimer': typeof DisclaimerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/heatmap': typeof HeatmapRoute
  '/indices': typeof IndicesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-signup': typeof VerifySignupRoute
  '/dashboard/ai': typeof DashboardAiRouteWithChildren
  '/dashboard/heatmap': typeof DashboardHeatmapRoute
  '/dashboard/paper-trading': typeof DashboardPaperTradingRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/recommendations': typeof DashboardRecommendationsRoute
  '/dashboard/search': typeof DashboardSearchRoute
  '/dashboard/sentiment': typeof DashboardSentimentRoute
  '/dashboard/watchlist': typeof DashboardWatchlistRoute
  '/stock/$symbol': typeof StockSymbolRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/ai/$sessionId': typeof DashboardAiSessionIdRoute
  '/dashboard/stock/$symbol': typeof DashboardStockSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/heatmap': typeof HeatmapRoute
  '/indices': typeof IndicesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-signup': typeof VerifySignupRoute
  '/dashboard/ai': typeof DashboardAiRouteWithChildren
  '/dashboard/heatmap': typeof DashboardHeatmapRoute
  '/dashboard/paper-trading': typeof DashboardPaperTradingRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/recommendations': typeof DashboardRecommendationsRoute
  '/dashboard/search': typeof DashboardSearchRoute
  '/dashboard/sentiment': typeof DashboardSentimentRoute
  '/dashboard/watchlist': typeof DashboardWatchlistRoute
  '/stock/$symbol': typeof StockSymbolRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/ai/$sessionId': typeof DashboardAiSessionIdRoute
  '/dashboard/stock/$symbol': typeof DashboardStockSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/disclaimer': typeof DisclaimerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/heatmap': typeof HeatmapRoute
  '/indices': typeof IndicesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-signup': typeof VerifySignupRoute
  '/dashboard/ai': typeof DashboardAiRouteWithChildren
  '/dashboard/heatmap': typeof DashboardHeatmapRoute
  '/dashboard/paper-trading': typeof DashboardPaperTradingRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/recommendations': typeof DashboardRecommendationsRoute
  '/dashboard/search': typeof DashboardSearchRoute
  '/dashboard/sentiment': typeof DashboardSentimentRoute
  '/dashboard/watchlist': typeof DashboardWatchlistRoute
  '/stock/$symbol': typeof StockSymbolRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/ai/$sessionId': typeof DashboardAiSessionIdRoute
  '/dashboard/stock/$symbol': typeof DashboardStockSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/dashboard'
    | '/disclaimer'
    | '/forgot-password'
    | '/heatmap'
    | '/indices'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/terms'
    | '/verify-signup'
    | '/dashboard/ai'
    | '/dashboard/heatmap'
    | '/dashboard/paper-trading'
    | '/dashboard/profile'
    | '/dashboard/recommendations'
    | '/dashboard/search'
    | '/dashboard/sentiment'
    | '/dashboard/watchlist'
    | '/stock/$symbol'
    | '/dashboard/'
    | '/dashboard/ai/$sessionId'
    | '/dashboard/stock/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/disclaimer'
    | '/forgot-password'
    | '/heatmap'
    | '/indices'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/terms'
    | '/verify-signup'
    | '/dashboard/ai'
    | '/dashboard/heatmap'
    | '/dashboard/paper-trading'
    | '/dashboard/profile'
    | '/dashboard/recommendations'
    | '/dashboard/search'
    | '/dashboard/sentiment'
    | '/dashboard/watchlist'
    | '/stock/$symbol'
    | '/dashboard'
    | '/dashboard/ai/$sessionId'
    | '/dashboard/stock/$symbol'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/dashboard'
    | '/disclaimer'
    | '/forgot-password'
    | '/heatmap'
    | '/indices'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/terms'
    | '/verify-signup'
    | '/dashboard/ai'
    | '/dashboard/heatmap'
    | '/dashboard/paper-trading'
    | '/dashboard/profile'
    | '/dashboard/recommendations'
    | '/dashboard/search'
    | '/dashboard/sentiment'
    | '/dashboard/watchlist'
    | '/stock/$symbol'
    | '/dashboard/'
    | '/dashboard/ai/$sessionId'
    | '/dashboard/stock/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DisclaimerRoute: typeof DisclaimerRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HeatmapRoute: typeof HeatmapRoute
  IndicesRoute: typeof IndicesRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  VerifySignupRoute: typeof VerifySignupRoute
  StockSymbolRoute: typeof StockSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-signup': {
      id: '/verify-signup'
      path: '/verify-signup'
      fullPath: '/verify-signup'
      preLoaderRoute: typeof VerifySignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indices': {
      id: '/indices'
      path: '/indices'
      fullPath: '/indices'
      preLoaderRoute: typeof IndicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmap': {
      id: '/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof HeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/stock/$symbol': {
      id: '/stock/$symbol'
      path: '/stock/$symbol'
      fullPath: '/stock/$symbol'
      preLoaderRoute: typeof StockSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/watchlist': {
      id: '/dashboard/watchlist'
      path: '/watchlist'
      fullPath: '/dashboard/watchlist'
      preLoaderRoute: typeof DashboardWatchlistRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sentiment': {
      id: '/dashboard/sentiment'
      path: '/sentiment'
      fullPath: '/dashboard/sentiment'
      preLoaderRoute: typeof DashboardSentimentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/search': {
      id: '/dashboard/search'
      path: '/search'
      fullPath: '/dashboard/search'
      preLoaderRoute: typeof DashboardSearchRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/recommendations': {
      id: '/dashboard/recommendations'
      path: '/recommendations'
      fullPath: '/dashboard/recommendations'
      preLoaderRoute: typeof DashboardRecommendationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/paper-trading': {
      id: '/dashboard/paper-trading'
      path: '/paper-trading'
      fullPath: '/dashboard/paper-trading'
      preLoaderRoute: typeof DashboardPaperTradingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/heatmap': {
      id: '/dashboard/heatmap'
      path: '/heatmap'
      fullPath: '/dashboard/heatmap'
      preLoaderRoute: typeof DashboardHeatmapRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai': {
      id: '/dashboard/ai'
      path: '/ai'
      fullPath: '/dashboard/ai'
      preLoaderRoute: typeof DashboardAiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/stock/$symbol': {
      id: '/dashboard/stock/$symbol'
      path: '/stock/$symbol'
      fullPath: '/dashboard/stock/$symbol'
      preLoaderRoute: typeof DashboardStockSymbolRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai/$sessionId': {
      id: '/dashboard/ai/$sessionId'
      path: '/$sessionId'
      fullPath: '/dashboard/ai/$sessionId'
      preLoaderRoute: typeof DashboardAiSessionIdRouteImport
      parentRoute: typeof DashboardAiRoute
    }
  }
}

interface DashboardAiRouteChildren {
  DashboardAiSessionIdRoute: typeof DashboardAiSessionIdRoute
}

const DashboardAiRouteChildren: DashboardAiRouteChildren = {
  DashboardAiSessionIdRoute: DashboardAiSessionIdRoute,
}

const DashboardAiRouteWithChildren = DashboardAiRoute._addFileChildren(
  DashboardAiRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAiRoute: typeof DashboardAiRouteWithChildren
  DashboardHeatmapRoute: typeof DashboardHeatmapRoute
  DashboardPaperTradingRoute: typeof DashboardPaperTradingRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardRecommendationsRoute: typeof DashboardRecommendationsRoute
  DashboardSearchRoute: typeof DashboardSearchRoute
  DashboardSentimentRoute: typeof DashboardSentimentRoute
  DashboardWatchlistRoute: typeof DashboardWatchlistRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardStockSymbolRoute: typeof DashboardStockSymbolRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiRoute: DashboardAiRouteWithChildren,
  DashboardHeatmapRoute: DashboardHeatmapRoute,
  DashboardPaperTradingRoute: DashboardPaperTradingRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardRecommendationsRoute: DashboardRecommendationsRoute,
  DashboardSearchRoute: DashboardSearchRoute,
  DashboardSentimentRoute: DashboardSentimentRoute,
  DashboardWatchlistRoute: DashboardWatchlistRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardStockSymbolRoute: DashboardStockSymbolRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DisclaimerRoute: DisclaimerRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HeatmapRoute: HeatmapRoute,
  IndicesRoute: IndicesRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  VerifySignupRoute: VerifySignupRoute,
  StockSymbolRoute: StockSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
